### ISSUE TITLE
тестирование памяти GDDR

### ISSUE THREAD

**Issue by MVV1983** [galkinvv/galkinvv.github.io#1]
Приветствую!
подскажите каким образом определяете вышедшие модули памяти на видеокартах.
занимаюсь ремонтом видеокарт, но конечно не на таком высоком уровне как вы=)!

**Comment by galkinvv** [comment]
Использую самописный скрипт https://github.com/galkinvv/galkinvv.github.io/blob/master/direct-mem-test.py

Внимание - ссылки ниже на конкретные сообщения, а не просто на тему! Вцелом там вся тема по делу, но тем не менее чтоб бяло ясно на что я ссылаюсь.

Описание ипользования - есть тут http://vlab.su/viewtopic.php?p=680492#p680492

Однако всё не так радужно - есть куча граблей с которыми не очень ясно что делать - http://vlab.su/viewtopic.php?p=714604#p714604

По дальнейшим вопросам прошу создавать темы в http://vlab.su/viewforum.php?f=48

Если тема по этому скрипту - после создания пинганите меня там ЛС 
http://vlab.su/ucp.php?i=pm&mode=compose&action=quotepost&p=680492
