### ISSUE TITLE
PowerXpressLoad registry setting?

### ISSUE THREAD

**Issue by DwarfFighterCleric** [galkinvv/galkinvv.github.io#2]
I just stumbled on this registry parameter in Windows under
HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\amdkmdag
called PowerXpressLoad  
  
has a default value of FFFFFFFF (maximum possible)  
  
Do you know what that does on the GPU or if it can be tweaked?

**Comment by galkinvv** [comment]
Unfortunately it's completely unknown to me.
